# Configuration for inference on SE(3) diffusion experiments.
defaults:
  - base
  - _self_

inference:

  predict_dir: ./inference_outputs/
  inference_subdir: run_${now:%Y-%m-%d}_${now:%H-%M-%S}
  task: forward_folding
  seed: 123
  use_gpu: True
  num_gpus: 4

  saved_ckpt_dir: ./saved_ckpts/frameflow

  forward_folding_ckpt_path: ./weights/last.ckpt

  also_fold_pmpnn_seq: False # whether to also fold the generated pmpnn seq for each structure
  write_sample_trajectories: False # whether to also save the trajectory of the generation process

  interpolant:
    min_t: 1e-2
    provide_kappa: False
    codesign_separate_t: True

    rots:
      corrupt: True
      sample_schedule: exp
      exp_rate: 10

    trans:
      corrupt: True
      pre_align: True
      train_schedule: linear
      sample_schedule: linear
      sample_temp: 1.0
      potential: null
      potential_t_scaling: False
      rog:
        weight: 20.0
        cutoff: 5.0
    aatypes:
      corrupt: True
      schedule: linear
      schedule_exp_rate: -3
      temp: 0.1
      noise: 0.0
      do_purity: False
      interpolant_type: masking
    sampling:
      num_timesteps: 500
      do_sde: False

    self_condition: True

  # Directory of software, weights, and outputs.  
  pmpnn_dir: ./ProteinMPNN

  folding:
    seq_per_sample: 1
    folding_model: esmf
    own_device: False
    pmpnn_path: ./ProteinMPNN/
    pt_hub_dir: ./.cache/torch/
    colabfold_path: path/to/colabfold-conda/bin/colabfold_batch # for AF2

  samples: